# Generated by Django 5.2.4 on 2026-07-16 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.staffmember'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['staff', 'start_time'], name='bookings_bo_staff_i_9aeb4c_idx'),
        ),
    ]
